// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace finfast_backend.Models;

[PrimaryKey("RegionCodigo", "Codigo")]
[Table("Ciudad")]
public partial class Ciudad
{
    [Key]
    public short RegionCodigo { get; set; }

    [Key]
    public short Codigo { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Nombre { get; set; }

    [InverseProperty("Ciudad")]
    public virtual ICollection<Comuna> Comunas { get; set; } = new List<Comuna>();

    [ForeignKey("RegionCodigo")]
    [InverseProperty("Ciudads")]
    public virtual Region RegionCodigoNavigation { get; set; }
}