// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace finfast_backend.Models;

[PrimaryKey("RegionCodigo", "CiudadCodigo", "Codigo")]
[Table("Comuna")]
public partial class Comuna
{
    [Key]
    public short RegionCodigo { get; set; }

    [Key]
    public short CiudadCodigo { get; set; }

    [Key]
    public short Codigo { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Nombre { get; set; }

    public int CodigoPostal { get; set; }

    public int CodigoLibroClaseElectronico { get; set; }

    [ForeignKey("RegionCodigo, CiudadCodigo")]
    [InverseProperty("Comunas")]
    public virtual Ciudad Ciudad { get; set; }

    [InverseProperty("Comuna")]
    public virtual ICollection<Persona> Personas { get; set; } = new List<Persona>();
}