// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace finfast_backend.Models;

[Table("Persona")]
public partial class Persona
{
    [Key]
    public Guid Id { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string Run { get; set; }

    public int RunCuerpo { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string RunDigito { get; set; }

    [StringLength(95)]
    [Unicode(false)]
    public string Nombre { get; set; }

    [Required]
    [StringLength(45)]
    [Unicode(false)]
    public string Nombres { get; set; }

    [Required]
    [StringLength(25)]
    [Unicode(false)]
    public string ApellidoPaterno { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string ApellidoMaterno { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string Email { get; set; }

    public short SexoCodigo { get; set; }

    public DateOnly? FechaNacimiento { get; set; }

    public short? RegionCodigo { get; set; }

    public short? CiudadCodigo { get; set; }

    public short? ComunaCodigo { get; set; }

    [Column(TypeName = "text")]
    public string Direccion { get; set; }

    public int? Telefono { get; set; }

    [Column(TypeName = "text")]
    public string Observaciones { get; set; }

    [ForeignKey("RegionCodigo, CiudadCodigo, ComunaCodigo")]
    [InverseProperty("Personas")]
    public virtual Comuna Comuna { get; set; }

    [ForeignKey("SexoCodigo")]
    [InverseProperty("Personas")]
    public virtual Sexo SexoCodigoNavigation { get; set; }
}