// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using finfast_backend.Models;

namespace finfast_backend.Models
{
    public partial class PruebaTecnicaContext
    {

        [DbFunction("FormatInt", "dbo")]
        public static string FormatInt(int? Number)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetRunDigito", "dbo")]
        public static string GetRunDigito(int? RunCuerpo)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
