// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace finfast_backend.Models;

[Table("Region")]
public partial class Region
{
    [Key]
    public short Codigo { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Nombre { get; set; }

    [Required]
    [StringLength(40)]
    [Unicode(false)]
    public string NombreOficial { get; set; }

    public int CodigoLibroClaseElectronico { get; set; }

    [InverseProperty("RegionCodigoNavigation")]
    public virtual ICollection<Ciudad> Ciudads { get; set; } = new List<Ciudad>();
}