// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace finfast_backend.Models;

[Table("Sexo")]
public partial class Sexo
{
    [Key]
    public short Codigo { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Nombre { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string Letra { get; set; }

    [InverseProperty("SexoCodigoNavigation")]
    public virtual ICollection<Persona> Personas { get; set; } = new List<Persona>();
}